// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateDepartureTime(arg1, arg2) {
  return window['go']['main']['App']['CalculateDepartureTime'](arg1, arg2);
}

export function CreateCalendarEvent(arg1) {
  return window['go']['main']['App']['CreateCalendarEvent'](arg1);
}
